[package]
name = "greed_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.23.1"
termion = "1.5.6"
tui = "0.18.0"
clap = "3.1.6"
rand = "0.8.5"
